name: graphview
description:  GraphView is used to display data in graph structures. It can display Tree layout, Directed and Layered graph. Useful for Family Tree, Hierarchy View.
version: 1.2.0
homepage: https://github.com/nabil6391/graphview

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: GHAITHSANS
      fonts:
        - asset: assets/fonts/GHAITHSANS/GHAITHSANS-REGULAR.OTF
          weight: 400
        - asset: assets/fonts/GHAITHSANS/GHAITHSANS-MEDIUM.OTF
          weight: 500
        - asset: assets/fonts/GHAITHSANS/GHAITHSANS-SEMIBOLD.OTF
          weight: 600
        - asset: assets/fonts/GHAITHSANS/GHAITHSANS-BOLD.OTF
          weight: 700
        - asset: assets/fonts/GHAITHSANS/GHAITHSANS-EXTRABOLD.OTF
          weight: 800
        - asset: assets/fonts/GHAITHSANS/GHAITHSANS-BLACK.OTF
          weight: 900
        - asset: assets/fonts/GHAITHSANS/GHAITHSANS-LIGHT.OTF
          weight: 300
        - asset: assets/fonts/GHAITHSANS/GHAITHSANS-EXTRALIGHT.OTF
          weight: 200
        - asset: assets/fonts/GHAITHSANS/GHAITHSANS-THIN.OTF
          weight: 100

