name: graphview
description:  GraphView is used to display data in graph structures. It can display Tree layout, Directed and Layered graph. Useful for Family Tree, Hierarchy View.
version: 1.2.0
homepage: https://github.com/nabil6391/graphview

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  fonts:
    - family: ghaithsans
      fonts:
        - asset: ../assets/fonts/ghaithsans/ghaithsans_regular.otf
          weight: 400
        - asset: ../assets/fonts/ghaithsans/ghaithsans_medium.otf
          weight: 500
        - asset: ../assets/fonts/ghaithsans/ghaithsans_semibold.otf
          weight: 600
        - asset: ../assets/fonts/ghaithsans/ghaithsans_bold.otf
          weight: 700
        - asset: ../assets/fonts/ghaithsans/ghaithsans_extrabold.otf
          weight: 800
        - asset: ../assets/fonts/ghaithsans/ghaithsans_black.otf
          weight: 900
        - asset: ../assets/fonts/ghaithsans/ghaithsans_light.otf
          weight: 300
        - asset: ../assets/fonts/ghaithsans/ghaithsans_extralight.otf
          weight: 200
        - asset: ../assets/fonts/ghaithsans/ghaithsans_thin.otf
          weight: 100

