// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-2q-j2veLLngIXjNlMlaY4f0l0l4xWOg',
    appId: '1:684970788591:web:4423d058b1851367323d1a',
    messagingSenderId: '684970788591',
    projectId: 'a-292e9',
    authDomain: 'a-292e9.firebaseapp.com',
    storageBucket: 'a-292e9.appspot.com',
    measurementId: 'G-GTD3PKXK3Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0J2CblvUejsualsy5RwSpYcMpH84mYAo',
    appId: '1:684970788591:android:6de27fe87021c3dd323d1a',
    messagingSenderId: '684970788591',
    projectId: 'a-292e9',
    storageBucket: 'a-292e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw1SsePYxxP2APw2TXsvcMPx0_eAc0Zvs',
    appId: '1:684970788591:ios:046c53a7f39e95ae323d1a',
    messagingSenderId: '684970788591',
    projectId: 'a-292e9',
    storageBucket: 'a-292e9.appspot.com',
    iosClientId: '684970788591-b41rfoaomj6geun5o0g6i3d5rppknf9u.apps.googleusercontent.com',
    iosBundleId: 'com.abrain.asl.asl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw1SsePYxxP2APw2TXsvcMPx0_eAc0Zvs',
    appId: '1:684970788591:ios:046c53a7f39e95ae323d1a',
    messagingSenderId: '684970788591',
    projectId: 'a-292e9',
    storageBucket: 'a-292e9.appspot.com',
    iosClientId: '684970788591-b41rfoaomj6geun5o0g6i3d5rppknf9u.apps.googleusercontent.com',
    iosBundleId: 'com.abrain.asl.asl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-2q-j2veLLngIXjNlMlaY4f0l0l4xWOg',
    appId: '1:684970788591:web:6d2adfda5c4d030e323d1a',
    messagingSenderId: '684970788591',
    projectId: 'a-292e9',
    authDomain: 'a-292e9.firebaseapp.com',
    storageBucket: 'a-292e9.appspot.com',
    measurementId: 'G-7LLFN6M2K9',
  );
}
